### ISSUE TITLE
trigger NOTIFY_RX in HAL_UART_RxTimeoutCallback() every time.

### ISSUE THREAD

**Issue by meishaoming** [juan0fran/STM32L4_CC1101#1]
Hi, juan0fran, 

Thank for you code cause it inspired me a lot.

i found that every 3 uart bit time, it will trigger a UART RTO interrupt. In HAL_UART_RxTimeoutCallback() set IFACE_NOTIFY_RX single no matter there are data received.

i think most often there is no real data received, and it is no need to set the IFACE_NOTIFY_RX signal every time. 

is it better that set IFACE_NOTIFY_RX signal only while len > 0?

**Comment by juan0fran** [comment]
Hi meishaoming,

Thank you too for openning the issue. I am totally agree with you, IFACE_NOTIFY shall be triggered only if data has been received. Even tho, only on those cases where the amount of data received is equal to DMA_BUFFER_SIZE or DMA_BUFFER_SIZE_HALF the case that you propose happens. But yes, of course on that cases there is a signal raise that may not be there.

I will correct it in next versions, thank you!

**Comment by meishaoming** [comment]
Thank  you for your reply.
